Revert of Add PrivacyMode support to the QuicStreamFactory. (https://codereview.chromium.org/185773006/)
Reason for revert:
Reverted by request from kareng. It breaks the continuous official tests. 

../../net/tools/quic/quic_client_bin.cc: In function ‘int main(int, char**)’:
../../net/tools/quic/quic_client_bin.cc:76:67: error: no matching function for call to ‘net::QuicSessionKey::QuicSessionKey(std::string&, int32&, bool&)’
../../net/tools/quic/quic_client_bin.cc:76:67: note: candidates are:
../../net/quic/quic_session_key.h:23:3: note: net::QuicSessionKey::QuicSessionKey(const string&, uint16, bool, net::PrivacyMode)
../../net/quic/quic_session_key.h:23:3: note:   candidate expects 4 arguments, 3 provided
../../net/quic/quic_session_key.h:20:3: note: net::QuicSessionKey::QuicSessionKey(const net::HostPortPair&, bool, net::PrivacyMode)
../../net/quic/quic_session_key.h:20:3: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const net::HostPortPair&’
../../net/quic/quic_session_key.h:19:3: note: net::QuicSessionKey::QuicSessionKey()
../../net/quic/quic_session_key.h:19:3: note:   candidate expects 0 arguments, 3 provided
../../net/quic/quic_session_key.h:17:26: note: net::QuicSessionKey::QuicSessionKey(const net::QuicSessionKey&)
../../net/quic/quic_session_key.h:17:26: note:   candidate expects 1 argument, 3 provided

Original issue's description:
> Add PrivacyMode support to the QuicStreamFactory.
> 
> BUG=
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=259303

TBR=rtenneti@chromium.org,rch@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/211373004