Revert 284684 "Pepper: Delete FileDownloader in trusted plugin."
Reverting as broke chrome and chromeos dbg builders:
http://build.chromium.org/p/chromium.linux/builders/Linux%20Tests%20%28dbg%29%281%29/builds/32615/steps/browser_tests/logs/SuccessfulLoadUMA
[ RUN      ] NaClBrowserTestPnacl.SuccessfulLoadUMA
Xlib:  extension "RANDR" missing on display ":9".
Xlib:  extension "RANDR" missing on display ":9".
[18889:18889:0722/130648:WARNING:password_store_factory.cc(215)] Using
basic (unencrypted) store for password storage. See
http://code.google.com/p/chromium/wiki/LinuxPasswordStorage for more
information about password storage options.
HTTP server started on http://127.0.0.1:56115...
sending server_data: {"host": "127.0.0.1", "port": 56115} (36 bytes)
[9:10:0722/130650:ERROR:pnacl_translation_resource_host.cc(135)] Got
invalid platformfilefortransit
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/debug/vector:461:
    error: attempt to insert into container with an iterator from a
    different container.

Objects involved in the operation:
sequence "this" @ 0x0x392ba6c93260 {
}
iterator "__position" @ 0x0x7fff9ff24e20 {
  state = past-the-end;
  references sequence @ 0x0x7fff9ff24e20
}
[18889:18938:0722/130651:WARNING:raw_channel_posix.cc(214)] recvmsg:
Connection reset by peer
BrowserTestBase signal handler received SIGTERM. Backtrace:
#0 0x7fe4bf491cee base::debug::StackTrace::StackTrace()
#1 0x000004af93fa content::(anonymous
namespace)::DumpStackTraceSignalHandler()
#2 0x7fe4b68074a0 \u003Cunknown>
#3 0x7fe4b68b9a43 __poll
#4 0x7fe4b76faff6 \u003Cunknown>
#5 0x7fe4b76fb124 g_main_context_iteration
#6 0x7fe4bf44ff75 base::MessagePumpGlib::Run()
#7 0x7fe4bf54b1f0 base::MessageLoop::RunHandler()
#8 0x7fe4bf5b18e2 base::RunLoop::Run()
#9 0x000004b63969 content::RunThisRunLoop()
#10 0x000004b638fa content::RunMessageLoop()
#11 0x000004b0ea15 content::JavascriptTestObserver::Run()
#12 0x000001312927 NaClBrowserTestBase::RunJavascriptTest()
#13 0x000001312a48 NaClBrowserTestBase::RunLoadTest()
#14 0x00000130f514 (anonymous
namespace)::NaClBrowserTestPnacl_SuccessfulLoadUMA_Test::RunTestOnMai
...

> Pepper: Delete FileDownloader in trusted plugin.
> 
> This simplifies PnaclCoordinator considerably and reduces the total
> amount of code in the trusted plugin.
> 
> BUG=239656
> 
> Review URL: https://codereview.chromium.org/393693004

TBR=teravest@chromium.org

Review URL: https://codereview.chromium.org/406323003