Reland "Clean up ui_test_support target."
Original description from r265125:

1- Remove exclusion rule for cocoa files, this target does not have more
cocoa files.
2- Remove dependency on chromeos library, this target does not need to
link with them anymore.

It was reverted in r265137 because it caused a breakage in ash_unittests in
chromeos build, not sure why CQ didn't catch this.

obj/ash/display/ash_unittests.projecting_observer_chromeos_unittest.o:projecting_observer_chromeos_unittest.cc:function
testing::internal::TestFactoryImpl<ash::ProjectingObserverTest_CheckStopProjectingAfterDisconnectingSecondOutput_Test>::CreateTest():
error: undefined reference to
'chromeos::FakePowerManagerClient::FakePowerManagerClient()'
obj/ash/display/ash_unittests.projecting_observer_chromeos_unittest.o:projecting_observer_chromeos_unittest.cc:function
testing::internal::TestFactoryImpl<ash::ProjectingObserverTest_CheckStopProjectingAfterClosingAllCastingSessions_Test>::CreateTest():
error: undefined reference to
'chromeos::FakePowerManagerClient::FakePowerManagerClient()'

BUG=331829
TEST=ui_unittests,content_unittests,ash_unittests links
TBR=ben@chromium.org,nona@chromium.org,avi@chromium.org

Review URL: https://codereview.chromium.org/246283002