Fix a crash when clicking "Distill page" menu item.
Currently, Chrome Shell for Android crashes when we click the "Distill page"
menu item(see the below logs for details). Actually, this is due to the fact
described in https://codereview.chromium.org/333823004, but it seems there is
a possibility that the given tab view is not equal to |mCurrentView|. So we
need to update |mCurrentView| when TabObserver.onContentChanged() is called.

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:3562)
    at android.view.ViewGroup.addView(ViewGroup.java:3415)
    at android.view.ViewGroup.addView(ViewGroup.java:3360)
    at android.view.ViewGroup.addView(ViewGroup.java:3336)
    at org.chromium.chrome.shell.TabManager.setupContent(TabManager.java:148)
    at org.chromium.chrome.shell.TabManager.access$500(TabManager.java:27)
    at org.chromium.chrome.shell.TabManager$3.onContentChanged(TabManager.java:137)
    at org.chromium.chrome.browser.Tab.swapContentViewCore(Tab.java:1071)
    at org.chromium.chrome.browser.Tab.swapWebContents(Tab.java:1034)
    at org.chromium.chrome.browser.dom_distiller.DomDistillerTabUtils.nativeDistillCurrentPageAndView(Native Method)
    at org.chromium.chrome.browser.dom_distiller.DomDistillerTabUtils.distillCurrentPageAndView(DomDistillerTabUtils.java:27)
    at org.chromium.chrome.shell.ChromeShellActivity.onOptionsItemSelected(ChromeShellActivity.java:309)
    at org.chromium.chrome.browser.appmenu.AppMenuHandler.onOptionsItemSelected(AppMenuHandler.java:150)
    at org.chromium.chrome.browser.appmenu.AppMenu.onItemClick(AppMenu.java:177)
    at org.chromium.chrome.browser.appmenu.AppMenuAdapter$1.onClick(AppMenuAdapter.java:114)
    at android.view.View.performClick(View.java:4438)
    at android.view.View$PerformClick.run(View.java:18422)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5001)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)

BUG=none

Review URL: https://codereview.chromium.org/336433006