[Telemetry] Add two missing methods to ios browser finder.
Fixes:
  AttributeError: 'module' object has no attribute 'SelectDefaultBrowser'

BUG=

Review URL: https://codereview.chromium.org/355513002