Revert of Fix sticky keys crash when handling synthetic events without a native event. (https://codereview.chromium.org/227113009/)
Reason for revert:
Breaks compile on Linux ChromiumOS (Clang dbg) 

.../sticky_keys_unittest.cc:848:3:error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
  dispatcher->OnEventFromSource(kev.get());
(and 2 more)

link: http://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20%28Clang%20dbg%29/builds/922/

Original issue's description:
> Fix sticky keys crash when handling synthetic events without a native event.
> 
> BUG=358270
> TEST=modified tests
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=262465

TBR=sadrul@chromium.org,tengs@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=358270

Review URL: https://codereview.chromium.org/229053002