Revert of Add creation of v14 compatible resources to process_resources.py (https://codereview.chromium.org/321453002/)
Reason for revert:
This is causing instrumentation-yakju-clankium-tot and clang-clankium-tot-builder (downstream) to fail with the following error message:

FAILED: cd ../../clank/native/framework; python ../../../build/android/gyp/process_resources.py --android-sdk /b/build/slave/instrumentation-yakju-clankium-tot/build/src/third_party/android_tools/sdk//platforms/android-19 --android-sdk-tools /b/build/slave/instrumentation-yakju-clankium-tot/build/src/third_party/android_tools/sdk//build-tools/19.0.0 --android-manifest ../../../clank/java/apps/deviceextras/AndroidManifest.xml --dependencies-res-dirs "" --extra-res-packages "" --extra-r-text-files "" --proguard-file ../../../out/Debug/device_extras_apk/proguard.txt --resource-dir ../../../clank/java/apps/deviceextras/res --res-v14-compatibility-dir ../../../out/Debug/device_extras_apk/res_v14_compatibility --crunch-output-dir ../../../out/Debug/device_extras_apk/res --R-dir ../../../out/Debug/device_extras_apk/gen --stamp ../../../out/Debug/device_extras_apk/codegen.stamp
Traceback (most recent call last):
  File "../../../build/android/gyp/process_resources.py", line 217, in <module>
    main()
  File "../../../build/android/gyp/process_resources.py", line 166, in main
    options.v14_verify_only)
  File "/b/build/slave/instrumentation-yakju-clankium-tot/build/src/build/android/gyp/generate_v14_compatible_resources.py", line 335, in GenerateV14Resources
    ErrorIfStyleResourceExistsInDir(input_dir)
  File "/b/build/slave/instrumentation-yakju-clankium-tot/build/src/build/android/gyp/generate_v14_compatible_resources.py", line 107, in ErrorIfStyleResourceExistsInDir
    '-v17 directory. Please refer to '
Exception: error: style file /b/build/slave/instrumentation-yakju-clankium-tot/build/src/clank/java/apps/deviceextras/res/values/styles.xml should be under /b/build/slave/instrumentation-yakju-clankium-tot/build/src/clank/java/apps/deviceextras/res/values-v17 directory. Please refer to http://crbug.com/243952 for the details.

I don't know resource loading well enough to tell if that's a legitimate issue or not; so for now reverting this to fix the build bots, and if it is a legitimate issue then ideally it could be fixed before relanding this?

Original issue's description:
> Add creation of v14 compatible resources to process_resources.py
> 
> There are a lot of steps in processing resources and preparing them for
> packaging. It will be easier if these are all done by the same script.
> 
> BUG=375431,359249
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=275401

TBR=newt@chromium.org,cjhopman@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=375431,359249

Review URL: https://codereview.chromium.org/314363002