Revert 261778 "When "linux_use_gold_binary" is set, we now use g..."
Broke ASAN builders: e.g. http://build.chromium.org/p/chromium.memory/builders/Linux%20ASan%2BLSan%20Builder/builds/2502/steps/runhooks/logs/stdio

 
________ running '/usr/bin/python src/build/gyp_chromium' in '/b/build/slave/Linux_ASan_LSan_Builder/build'
Error: Command /usr/bin/python src/build/gyp_chromium returned non-zero exit status 1 in /b/build/slave/Linux_ASan_LSan_Builder/build
Updating projects from gyp files...
/bin/sh: 1: clang++: not found
compiler_version.py failed to execute: clang++ -Xassembler --version -x assembler -c /dev/null
Command 'clang++ -Xassembler --version -x assembler -c /dev/null' returned non-zero exit status 127
gyp: Call to 'python ../build/compiler_version.py assembler' returned exit status 1.
program finished with exit code 2
elapsedTime=6.794917


> When "linux_use_gold_binary" is set, we now use gold from third_party/binutils rather than third_party/gold (allowing us to remove third_party/gold dependency).
> 
> As third_party/binutils is 2.24, this also satisfies the binutils version requirements for Debug Fission. Thus, when building with clang on Ubuntu Precise it should now be enabled. This should cause a significant speedup in linking for most chrome developers on Linux.
> 
> Requires;
>  * https://codereview.chromium.org/209853003/ - Adding binutils as a DEPS to allow DebugFission on Ubuntu Precise when compiling with clang.
> 
> BUG=352046
> 
> Review URL: https://codereview.chromium.org/196573022

TBR=mithro@mithis.com

Review URL: https://codereview.chromium.org/224933007