Fix a lint issue with UsbMidiDeviceAndroid.java.
Currently, the lint warns at:
Error: Call requires API level 18 (current min is 14):
    android.hardware.usb.UsbDeviceConnection#bulkTransfer [NewApi]

So we need to add @TargetApi to suppress this lint error.

BUG=327768

Review URL: https://codereview.chromium.org/276943002