Revert 284518 "Disable a flaky test."
This broke compile on android:
http://build.chromium.org/p/chromium/builders/Android/builds/26268/steps/compile/logs/stdio

../android_webview/javatests/src/org/chromium/android_webview/test/AwContentsClientShouldOverrideUrlLoadingTest.java:794:
cannot find symbol
symbol  : class DisabledTest
location: class
org.chromium.android_webview.test.AwContentsClientShouldOverrideUrlLoadingTest
    @DisabledTest
     ^
1 error

> Disable a flaky test.
> 
> BUG=395817
> TEST=none
> TBR=joth
> 
> Review URL: https://codereview.chromium.org/408043002

TBR=pkasting@chromium.org

Review URL: https://codereview.chromium.org/407003002