Revert of Consolidate attachment URL construction. (https://codereview.chromium.org/355093002/)
Reason for revert:
Broke compile on ChromiumOS on Linux:

../../chrome/browser/sync/profile_sync_components_factory_impl.cc: In member function 'virtual scoped_ptr<syncer::AttachmentService> ProfileSyncComponentsFactoryImpl::CreateAttachmentService(syncer::AttachmentService::Delegate*)':
../../chrome/browser/sync/profile_sync_components_factory_impl.cc:648:44: error: 'url_prefix' was not declared in this scope
ninja: build stopped: subcommand failed.

http://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Full/builds/6230/steps/compile/logs/stdio

Original issue's description:
> Consolidate attachment URL construction.
> 
> Fix bug where attachment URLs could end up with too many slashes.
> 
> BUG=
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=280193

TBR=pavely@chromium.org,maniscalco@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/356953009