Revert of Update V8 to version 3.26.9 (based on bleeding_edge revision r20585). (https://codereview.chromium.org/230423002/)
Reason for revert:
suspected cause of chromiumos breakage 

compile failures like

chromeos-chrome-36.0.1933.0_alpha-r1: .../src/v8/src/objects.h:4021:64: error: cannot call member function 'v8::internal::Object* v8::internal::FixedArray::get(int)' without object
chromeos-chrome-36.0.1933.0_alpha-r1:      return Smi::cast(FixedArray::get(kNextEnumerationIndexIndex))->value();

link: http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28x86%29/builds/20941/steps/cbuildbot/logs/stdio

Original issue's description:
> Update V8 to version 3.26.9 (based on bleeding_edge revision r20585).
> 
> TBR=dcarney@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=262675

TBR=dcarney@chromium.org,machenbach@chromium.org
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/230703003