Revert 284531 "NaCl: Update revision in DEPS, r13456 -> r13506"
This broke linux builder:
http://build.chromium.org/p/chromium.linux/buildstatus?builder=Linux%20Builder%20%28dbg%29&number=75554

[1147/10681 | 99.521] CXX
obj/net/disk_cache/simple/net.simple_net_log_parameters.o
FAILED: cd ../../chrome/test/data/nacl; python
../../../../native_client/build/build_nexe.py -t
../../../../out/Debug/gen/sdk/ --arch x86-32 --build newlib_translate
--root ../../../.. --name
../../../../out/Debug/ppapi_ppb_instance_pnacl_newlib_x32.nexe
"--link_flags=
-Wl,-L../../../../out/Debug/gen/tc_pnacl_translate/lib-x86-32"
../../../../out/Debug/nacl_test_data/pnacl/ppapi_ppb_instance_newlib_pnacl.pexe
/b/build/slave/Linux_Builder__dbg_/build/src/out/Debug/gen/sdk/linux_x86/pnacl_newlib/host_x86_32/bin/le32-nacl-ld.gold:error:
cannot open
../../../../out/Debug/gen/tc_pnacl_translate/lib-x86-32/libpnacl_irt_shim.a:
No such file or directory
/b/build/slave/Linux_Builder__dbg_/build/src/out/Debug/gen/sdk/linux_x86/pnacl_newlib/lib-x86-32/crtbegin.o:/mnt/data/b/build/slave/nacl-toolchain/build/native_client/toolchain_build/out/libs_support_native_x86_32_install/lib-x86-32/crtbegin.o---crtbegin.c---.expand.po:function
__pnacl_start:error: undefined reference to '_pnacl_wrapper_start'
../../../../out/Debug/gen/sdk/linux_x86/pnacl_newlib/bin/pnacl-translate
-arch x86-32
../../../../out/Debug/nacl_test_data/pnacl/ppapi_ppb_instance_newlib_pnacl.pexe
-o ../../../../out/Debug/ppapi_ppb_instance_pnacl_newlib_x32.nexe
-Wl,-L../../../../out/Debug/gen/tc_pnacl_translate/lib-x86-32
FAILED: Command
'['../../../../out/Debug/gen/sdk/linux_x86/pnacl_newlib/bin/pnacl-translate',
'-arch', 'x86-32',
'../../../../out/Debug/nacl_test_data/pnacl/ppapi_ppb_instance_newlib_pnacl.pexe',
'-o',
'../../../../out/Debug/ppapi_ppb_instance_pnacl_newlib_x32.nexe',
'-Wl,-L../../../../out/Debug/gen/tc_pnacl_translate/lib-x86-32']'
returned non-zero exit status 1
ninja: build stopped: subcommand failed.

> NaCl: Update revision in DEPS, r13456 -> r13506
> 
> This pulls in the following Native Client changes:
> 
> r13457: (dyen) LLVM Regression tests check for build files instead of empty dirs.
> r13458: (noelallen) Update and add GN files to build sel_ldr.
> r13459: (jvoung) Remove env cleanser references to obsolete env vars.
> r13460: (jfb) PNaCl: Update LLVM revision in pnacl/COMPONENT_REVISIONS
> r13461: (hamaji) Non-SFI Mode: Add prctl syscall wrapper
> r13462: (hamaji) Non-SFI Mode: Implement IRT fstat
> r13463: (hamaji) Correct the return type of TestSuite in timefuncs_test
> r13464: (hamaji) syscall_test: Do not test st_atime in the test for fstat
> r13465: (earthdok) Implement initial MSan support. Also, adjust ASan build flags.
> r13466: (dschuff) pnacl-ld: Do not attempt to parse ELF or bitcode files as linker scripts
> r13467: (jvoung) Remove NaClSrpcIsStandalone() function.
> r13468: (dschuff) Make testing architecture explicit PNaCl toolchain buildbot script
> r13469: (dschuff) Stub out pnacl-opt and pnacl-finalize tools for scons built_elsewhere=1
> r13470: (dschuff) Update revision for PNaCl r13392->r13466
> r13471: (noelallen) Build nacl_bootstrap_helper and test with GN scons
> r13472: (dschuff) Build PNaCl with mingw again
> r13473: (earthdok) Zap the NaClSignalContext struct in SignalCatch.
> r13474: (dschuff) Update revision for PNaCl r13466->r13472
> r13475: (sehr) Munge nacl_helper_bootstrap using python rather than libelf
> r13476: (sky) Changes scan_sources not to output on bogus directory
> r13477: (dschuff) Reduce debugging metadata for pexe builds in Chrome
> r13480: (jfb) PNaCl: Update LLVM revision in pnacl/COMPONENT_REVISIONS
> r13481: (hidehiko) Align at 16 bytes for stack for created thread.
> r13484: (jfb) Revert "Munge nacl_helper_bootstrap using python rather than libelf"
> r13485: (ncbray) Fix untrusted.gypi and build_nexe.py
> r13486: (teravest) Split nacl_defines to an importable .gni file.
> r13487: (dyen) Actually make package_version include logs when argument is set.
> r13488: (jfb) Update revision for PNaCl r13472->r13480
> r13489: (hidehiko) Wrap irt_interfaces.h by extern "C".
> r13490: (hidehiko) Non-SFI Mode: Implement irt_mprotect.
> r13493: (jvoung) Revert "Non-SFI Mode: Implement irt_mprotect."
> r13494: (noelallen) Add per-file OWNERS for .gn in this sub directory since per-file only works on the directory the OWNERS is in.
> r13495: (noelallen) Fix vc_toolchain.py paths.
> r13496: (noelallen) Revert of 7e955d3ab6159dc05a7f255c6daf03847809414a
> r13497: (dyen) Implemented Exists for pynacl.LocalStorageCache.
> r13500: (hidehiko) Non-SFI Mode: Make elf_loader usable from Chrome.
> r13503: (jvoung) PNaCl: Update compiler-rt revision in pnacl/COMPONENT_REVISIONS
> r13504: (sehr) Munge nacl_helper_bootstrap using python rather than libelf
> r13505: (dschuff) Roll PNaCl toolchain revision back to r13466
> r13506: (dschuff) Revert "Fix untrusted.gypi and build_nexe.py"
> 
> BUG=none
> TEST=browser_tests and nacl_integration
> CQ_EXTRA_TRYBOTS=tryserver.chromium:linux_nacl_sdk_build
> (omitting linux_rel_precise32 and linux_arm_cross_compile because they're currently broken)
> 
> Review URL: https://codereview.chromium.org/404663002

TBR=mseaborn@chromium.org

Review URL: https://codereview.chromium.org/409733002